THREAT_KEYWORDS = [
    # Original keywords
    'urgent',
    'verify',
    'social security',
    'irs',
    'bank account',
    'compromised',
    'suspicious',
    'immediately',
    'gift card',
    'warrant',
    'arrest',
    'fee',
    'winner',
    'lottery',
    'inheritance',
    'secret',
    'wire transfer',
    'access',
    'password',
    'account',
    'security',
    'ssn',
    'accident',
    'activity',
    'alert',
    'amazon',
    'anydesk',
    'asap',
    'attachment',
    'attempt',
    'background check',
    'bank transfer',
    'benefits',
    'bitcoin',
    'btc',
    'call back',
    'call this number',
    'card compromised',
    'cash app',
    'claim',
    'click the link',
    'collection agency',
    'computer infected',
    'confidential',
    'confirm',
    'confirmation code',
    'congratulations',
    'court',
    'credit card',
    'crypto',
    'deadline',
    'debit card',
    'delivery',
    'deposit',
    'disaster',
    'donation',
    'download',
    'emergency',
    'encrypted',
    'ethereum',
    'exe file',
    'expired',
    'facebook',
    'family emergency',
    'fedex',
    'final notice',
    'final warning',
    'fine',
    'follow this link',
    'fraud',
    'free',
    'gift cards',
    'google',
    'government',
    'guaranteed',
    'help',
    'identity',
    'infected',
    'information',
    'install',
    'investment',
    'jail',
    'legal',
    'locked account',
    'login',
    'malware',
    'medicare',
    'microsoft',
    'money',
    'moneygram',
    'nigerian prince',
    'offer',
    'overdue',
    'payment',
    'paypal',
    'penalty',
    'personal information',
    'phishing',
    'police',
    'problem',
    'processing fee',
    'prize',
    'remote access',
    'request',
    'required',
    'reward',
    'safe',
    'scan',
    'secure',
    'send money',
    'server',
    'service',
    'social media',
    'software',
    'support',
    'suspended',
    'tax',
    'threat',
    'transfer',
    'unauthorized',
    'update',
    'ups',
    'usps',
    'venmo',
    'virus',
    'warning',
    'western union',
    'windows',
    'wire money',
    'zelle'
]


SIMULATED_TRANSCRIPT_PARTS = [
    "Hello, how are you today?",
    "We're calling about your car's extended warranty.",
    "This is an urgent message regarding your bank account.",
    "We need you to verify your personal information.",
    "There has been suspicious activity on your social security number.",
    "You need to act immediately to resolve this issue.",
    "Can you confirm your mother's maiden name?",
    "You have been selected as a grand prize winner!",
    "To claim your prize, you just need to pay a small processing fee.",
    "The only way to pay the fee is with a gift card.",
    "We've detected a problem with your computer, we can fix it if you grant us access.",
    "This is the IRS, and there is a warrant for your arrest unless you pay now.",
    "What a lovely day for a walk in the park.",
    "I'm going to the grocery store later, do you need anything?",
    "Remember to call your grandchildren this weekend.",
    "We need you to send a wire transfer to a secure account."
]